# Numpy

Полезные ссылки
* https://www.kaggle.com/code/landlord/numpy-tutorial
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* https://www.kaggle.com/code/themlphdstudent/learn-numpy-numpy-50-exercises-and-solution

## Задачи

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python. Решение должно опираться исключительно на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` Выведите на экран первые 10 строк массива.

In [13]:
import numpy as np
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
print("---")
print(data[:10])

---
[[1.27244e+05 6.00000e+01 1.60000e+01]
 [2.38910e+04 2.50000e+01 7.00000e+00]
 [9.47460e+04 1.00000e+01 6.00000e+00]
 [6.76600e+04 5.00000e+00 6.00000e+00]
 [1.57911e+05 6.00000e+01 1.40000e+01]
 [1.52828e+05 4.00000e+01 7.00000e+00]
 [3.39410e+04 1.80000e+01 9.00000e+00]
 [4.46597e+05 1.50000e+01 5.00000e+00]
 [3.66174e+05 7.00000e+00 9.00000e+00]
 [7.42050e+04 2.00000e+01 7.00000e+00]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [14]:
import numpy as np
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
IDless_data = data[:, 1:]
print("---")
mean_values = np.mean(IDless_data, axis=0)
min_values = np.min(IDless_data, axis=0)
max_values = np.max(IDless_data, axis=0)
median_values = np.median(IDless_data, axis=0)
print(f"Mean: {mean_values}")
print(f"Min: {min_values}")
print(f"Max: {max_values}")
print(f"Median: {median_values}")


---
Mean: [2.16010017e+04 9.05528000e+00]
Min: [0. 1.]
Max: [2.14748365e+09 3.90000000e+01]
Median: [40.  9.]


3. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [18]:
import numpy as np
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
zero_minutes_recipies = np.sum(data [:, 1] == 0)
print(f"Zero-minutes recipies count: {zero_minutes_recipies}")
data[:, 1][data[:, 1] == 0] = 1
zero_minutes_recipies = np.sum(data[:, 1] == 0)
print(f"Zero-minutes recipies count after replacing: {zero_minutes_recipies}")

Zero-minutes recipies count: 479
Zero-minutes recipies count after replacing: 0


4. Посчитайте, сколько уникальных рецептов находится в датасете.

In [21]:
import numpy as np
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
unique_recipies = np.unique(data[:, 0])
print(f"Unique recipies count: {len(unique_recipies)}")

Unique recipies count: 100000


5. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [22]:
import numpy as np
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
unique_ingredients = np.unique(data[:, 2])
print(f"Unique ingredients count: {len(unique_ingredients)}")
print(f"List of unique ingredients: {unique_ingredients}")


Unique ingredients count: 37
List of unique ingredients: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 37.
 39.]


6. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [26]:
import numpy as np
print("---")
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
recipies_less_than_five = data[data[:, 2] <= 5]
print(f"Recipies less than five ingredients count (first 10): {recipies_less_than_five[:10]}")

---
Recipies less than five ingredients count (first 10): [[4.46597e+05 1.50000e+01 5.00000e+00]
 [2.04134e+05 5.00000e+00 3.00000e+00]
 [2.56230e+04 6.00000e+00 4.00000e+00]
 [4.84223e+05 1.80000e+01 4.00000e+00]
 [6.31500e+04 2.50000e+02 4.00000e+00]
 [7.04530e+04 2.50000e+01 4.00000e+00]
 [6.68420e+04 2.00000e+00 4.00000e+00]
 [3.37928e+05 5.50000e+01 4.00000e+00]
 [1.40245e+05 5.00000e+00 5.00000e+00]
 [7.53130e+04 6.03000e+02 5.00000e+00]]


7. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [29]:
import numpy as np
print("---")
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
data[:, 1][data[:, 1] == 0] = 1 #избежать деление на ноль
minutes = data[:, 1]
ingredients = data[:, 2]
ingredients_per_minute = ingredients / minutes
print(f"Ingredients per minute (first 10): {ingredients_per_minute[:10]}")
print(f"Max ingredients per minute: {np.max(ingredients_per_minute)}")


---
Ingredients per minute (first 10): [0.26666667 0.28       0.6        1.2        0.23333333 0.175
 0.5        0.33333333 1.28571429 0.35      ]
Max ingredients per minute: 24.0


8. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [32]:
import numpy as np
print("---")
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
sorted_data = data[data[:, 1].argsort()[::-1]]
top_100_by_minutes = sorted_data[:100]
print(f"Average ingredient count in top 100 recipies by longevity: {np.average(top_100_by_minutes[:, 2])}")

---
Average ingredient count in top 100 recipies by longevity: 6.63


9. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [34]:
import numpy as np
print("---")
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
data_random = data[np.random.choice(data.shape[0], size = 10, replace = False)]
print(f"Random recipies: {data_random}")


---
Random recipies: [[8.79780e+04 6.00000e+01 1.00000e+01]
 [1.63301e+05 5.00000e+01 1.00000e+01]
 [4.82061e+05 3.00000e+01 1.60000e+01]
 [4.91977e+05 4.00000e+01 1.20000e+01]
 [3.99560e+04 5.00000e+00 3.00000e+00]
 [4.12524e+05 6.00000e+01 7.00000e+00]
 [4.42947e+05 2.00000e+01 1.00000e+01]
 [2.49806e+05 3.00000e+01 1.10000e+01]
 [1.51557e+05 7.40000e+02 1.20000e+01]
 [1.54265e+05 9.00000e+01 7.00000e+00]]


10. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [38]:
import numpy as np
print("---")
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
avg_ingredients = np.average(data[:, 2])
print(f"Average ingredient count: {avg_ingredients}")
less_than_avg_ingredients = data[data[:, 2] < avg_ingredients]
percentage = (len(less_than_avg_ingredients) / data.shape[0]) * 100
print(f"Percentage: {percentage}%")

---
Average ingredient count: 9.05528
Percentage: 58.802%


11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [40]:
import numpy as np
print("---")
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
is_simple = (data[:, 1] <= 20) & (data[:, 2] <= 5)
data_with_flag = np.column_stack((data, is_simple.astype(int)))
print(f"Data with 'is simple' flag (first 10 rows): {data_with_flag[:10]}")

---
Data with 'is simple' flag (first 10 rows): [[1.27244e+05 6.00000e+01 1.60000e+01 0.00000e+00]
 [2.38910e+04 2.50000e+01 7.00000e+00 0.00000e+00]
 [9.47460e+04 1.00000e+01 6.00000e+00 0.00000e+00]
 [6.76600e+04 5.00000e+00 6.00000e+00 0.00000e+00]
 [1.57911e+05 6.00000e+01 1.40000e+01 0.00000e+00]
 [1.52828e+05 4.00000e+01 7.00000e+00 0.00000e+00]
 [3.39410e+04 1.80000e+01 9.00000e+00 0.00000e+00]
 [4.46597e+05 1.50000e+01 5.00000e+00 1.00000e+00]
 [3.66174e+05 7.00000e+00 9.00000e+00 0.00000e+00]
 [7.42050e+04 2.00000e+01 7.00000e+00 0.00000e+00]]


12. Выведите процент "простых" рецептов в датасете

In [2]:
%%time
import numpy as np
print("---")
data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=',', skip_header=1)
is_simple = (data[:, 1] <= 20) & (data[:, 2] <= 5)
is_simple_count = np.count_nonzero(is_simple)
print(f"Percentage of simple recipies: {is_simple_count/data.shape[0] * 100}%")

---
Percentage of simple recipies: 9.552%
CPU times: user 103 ms, sys: 17.7 ms, total: 120 ms
Wall time: 131 ms
